services:
  icecast:
    image: moul/icecast:latest
    platform: linux/amd64
    container_name: icecast
    restart: unless-stopped

    ports:
      - "8001:8000"

    volumes:
      - logs:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro

    environment:
      ICECAST_SOURCE_PASSWORD: changeme
      ICECAST_ADMIN_PASSWORD: changeme
      ICECAST_PASSWORD: changeme
      ICECAST_RELAY_PASSWORD: changeme

  liquidsoap_foo:
    image: savonet/liquidsoap:v2.3.0
    container_name: icecast-liquidsoap
    restart: unless-stopped
    depends_on:
      - icecast

    volumes:
      - "${PWD}/Downloads/Foo Fighters - Discography:/music:ro"
      - "./radio.liq:/etc/liquidsoap/radio.liq:ro"

    environment:
      - TZ=Europe/Berlin
    command: ["liquidsoap", "/etc/liquidsoap/radio.liq"]

volumes:
  logs:

networks:
  mediahub_net:
    external: true