version: "3.8"

services:
  sensu-backend:
    image: sensu/sensu:latest
    container_name: sensu-backend
    restart: unless-stopped
    networks:
      - proxy_net
      - sensu_net
    volumes:
      - sensu_state:/var/lib/sensu
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_net"

      # UI hinter Traefik
      - "traefik.http.routers.sensu.rule=Host(`sensu.elastic2ls.com`)"
      - "traefik.http.routers.sensu.entrypoints=websecure"
      - "traefik.http.routers.sensu.tls=true"
      - "traefik.http.routers.sensu.tls.certresolver=le"
      - "traefik.http.services.sensu.loadbalancer.server.port=3000"

networks:
  proxy_net:
    external: true
  sensu_net:
    driver: bridge

volumes:
  sensu_state:
