version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin

      # Web UI Passwort (in .env setzen)
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}

      # Optional: Upstream DNS
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"

      # Host-IP des Pi-hole (wichtig für korrekte Anzeige/Links)
      FTLCONF_LOCAL_IPV4: ${PIHOLE_HOST_IP}

    # DNS direkt am Host veröffentlichen (Traefik ist hierfür nicht zuständig)
    ports:
      - "192.168.6.1:53:53/udp"
      - "192.168.6.1:53:53/tcp"

    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d

    networks:
      - proxy_net

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_net"

      # Web UI über Traefik
      - "traefik.http.routers.pihole.rule=Host(`pi.elastic2ls.com`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=le"

      - "traefik.http.services.pihole.loadbalancer.server.port=80"

      # (Optional) Security Header / Proto
      - "traefik.http.middlewares.pihole-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.pihole.middlewares=pihole-headers@docker"

  unbound:
    image: mvance/unbound:1.20.0
    container_name: unbound
    restart: unless-stopped
    networks:
      - proxy_net
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro


networks:
  proxy_net:
    external: true

volumes:
  pihole_etc:
  pihole_dnsmasq:
